# Generated by Django 4.2.1 on 2023-10-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_alter_blooddonation_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonation',
            name='donation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
