# Generated by Django 4.2.1 on 2023-10-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customregistration_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customregistration',
            name='name',
        ),
        migrations.AlterField(
            model_name='customregistration',
            name='usertype',
            field=models.CharField(max_length=10),
        ),
    ]
